### ISSUE TITLE
Allow override of php::params

### ISSUE THREAD

**Issue by pcfreak30** [thias/puppet-php#36]
Presently I have had to edit the module to change package names, which should not be needed. Would like the ability to override params.

**Comment by thias** [comment]
I think this has been fixed for most names since the initial report. For instance, it's possible to override the `common_package_name` from hiera like this : 
```
---
php::common::common_package_name: 'php666-common'
```
Please reopen with details about which name(s) are still blocking you, if any.

**Comment by pcfreak30** [comment]
Not to be superstitious, but you might want to change the number in your previous comment example.
