### ISSUE TITLE
Problem with php5-fpm.sock permissions

### ISSUE THREAD

**Issue by habitullence** [thias/puppet-php#40]
I've set-up as another user using the example from the readme:
```
include php::fpm::daemon
php::fpm::conf { 'www':
  listen  => '127.0.0.1:9001',
  user    => 'nginx',
  # For the user to exist
  require => Package['nginx'],
}
```
The problem is php5-fpm.sock is still owned by the www-data user. Is something I can change with this module or should I be looking elsewhere?

**Comment by thias** [comment]
Correct : The current README has the relevant nginx configuration which you can reuse to get things working.
