### ISSUE TITLE
Module not installed

### ISSUE THREAD

**Issue by choonchernlim** [thias/puppet-php#51]
I have the following configuration:-
```
  php::ini { '/etc/php.ini':
    display_errors             => 'On',
    memory_limit               => '256M',
    post_max_size              => '15M',
    upload_max_filesize        =>'15M',
    date_timezone              => 'America/Menominee',
  }

  class { '::php::cli': }

  class { 'php::mod_php5': inifile => '/etc/php.ini' }

  php::module { [ 'enchant', 'ldap', 'gd', 'mysql']: }
```
When I did `php -m`, the following 4 modules weren't listed, thus not installed:

```
[PHP Modules]
bz2
calendar
Core
ctype
date
ereg
exif
filter
ftp
gettext
gmp
hash
iconv
libxml
openssl
pcntl
pcre
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
tokenizer
xml
zlib

[Zend Modules]
```
What should I change to get the modules installed and configured? Thank you.

**Comment by thias** [comment]
Without knowing which OS+version this is, and especially without any logs of the puppet run, I have no idea what the problem could be.

If you are still experiencing the issue, please reopen and provide the relevant sections of puppet's log.
